name: 🚀 Feature request
description: Suggest an idea for improving Filegrunt
title: "[FEATURE] <title>"
labels: [Enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you would like to add.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Is your proposal related to a problem?
      description: Provide a clear and concise description of what the problem is.
      placeholder: |
        I'm always frustrated when...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Let us know about other solutions you've tried or researched.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.
    validations:
      required: false
